spring.application.name=insurance-product-api

spring.datasource.url=jdbc:postgresql://localhost:5432/insurance
spring.datasource.username=postgres
spring.datasource.password=postgres227

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration